
import { test, expect } from '@playwright/test';

  test('PW test', async ({ page }) => {
  await page.goto('localhost:5173');
  await page.getByRole('button', { name: 'Tasks' }).click();
  await page.getByRole('button', { name: 'Add a Task' }).click();
  await page.getByRole('combobox').selectOption('4996a56e-6c57-4904-bda3-8890f4058ef0');
  await page.getByPlaceholder('Taskname').click();
  await page.getByPlaceholder('Taskname').fill('hdasdfhasf');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('div').filter({ hasText: 'nickelasdelete' }).getByRole('button', { name: 'delete' }).click();
  await page.getByRole('button', { name: 'Projects' }).click();
  await page.getByRole('button', { name: 'Add a project' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('button', { name: 'Add a project' }).click();
  await page.getByPlaceholder('project name').fill('f');
  await page.getByPlaceholder('project name').click();
  await page.getByPlaceholder('project name').fill('fsadsadas');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.locator('div').filter({ hasText: 'hej alla cooladelete' }).getByRole('button', { name: 'delete' }).click();
  await page.getByRole('button', { name: 'Tasks' }).click();
  await page.getByRole('button', { name: 'Add a Task' }).click();
  await page.getByRole('combobox').selectOption('b72e3054-a483-490e-98f2-547b0ead477f');
  await page.getByPlaceholder('Taskname').click();
  await page.getByPlaceholder('Taskname').fill('sadsadas');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('div').filter({ hasText: 'fsadsaadelete' }).getByRole('button', { name: 'delete' }).click();
  await page.getByRole('link', { name: 'Timer' }).click();
  await page.locator('div').filter({ hasText: 'kalaspuffarTime' }).getByRole('button', { name: 'Time' }).click();
  await page.getByRole('button', { name: 'Start' }).click();
  await page.getByRole('button', { name: 'Start' }).click();
  await page.getByRole('button', { name: 'stop' }).click();
  await page.locator('.css-sitk1c > .chakra-button').first().click();
  await page.locator('.css-sitk1c > .chakra-button').first().click();
  await page.getByText('hejasa').click();
  await page.locator('div').filter({ hasText: 'hejasaTime' }).getByRole('button', { name: 'Time' }).click();
  await page.getByRole('button', { name: 'Start' }).click();
  await page.getByRole('button', { name: 'stop' }).click();
  await page.getByRole('link', { name: 'Calendar' }).click();
  await page.locator('#root div').nth(1).click();
  await page.getByRole('textbox').fill('2023-03-19T19:40');
  await page.locator('div').filter({ hasText: 'test taskOpen Modal' }).getByRole('button', { name: 'Open Modal' }).click();
  await page.locator('[id="chakra-modal-\\:r9\\:"]').getByText('Close').click();
  await page.locator('div').filter({ hasText: 'test taskOpen Modal' }).getByRole('button', { name: 'Open Modal' }).click();
  await page.locator('[id="chakra-modal-\\:r9\\:"] button').first().click();
});